name: riverpod_test_case
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  flutter_smart_dialog: ^4.9.0+6
  dio:
  flutter_localizations:
    sdk: flutter
  intl:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
#  easy_localization: ^3.0.2-dev.5


flutter:
  generate: true
  uses-material-design: true